# Generated by Django 3.1.4 on 2021-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darwinstudiosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
